Корректное удаление сущностей с состовными первичными ключами
DigitalWand/digitalwand.admin_helper pull request #50
Opened 2016-11-25 12:35 UTC by nixmen

2016-12-02 14:12 UTC, lithium-li commented on lib/helper/AdminListHelper.php
>  			$className = $listHelperClass::getModel();
бесполезная переменная, нигде не используется

2016-12-02 14:16 UTC, lithium-li commented on lib/helper/AdminListHelper.php
> +					$listHelper = $listHelperClass;
зачем такая неочевидность? оберни это в else и добавь к if который в 520 строке

2016-12-02 14:18 UTC, lithium-li commented on lib/helper/AdminListHelper.php
> +					if ($listHelper) {
что-то я не вижу сценария когда хелпер будет пустой. Если пришло с окончанием «s» и нет хелпера разделов то логично что должна возникнуть ошибка

2016-12-02 14:26 UTC, senor-artemisio commented on lib/helper/AdminListHelper.php
> +					$this->getCommonPrimaryFilterById($className, $sectionClassName, $id)
$id уже передан в метод getCommonPrimaryFilterById и $this->pk() в нем тоже можно достать,  зачем делать array_merge? почему не сделать все внутри метода?

2016-12-05 12:50 UTC, senor-artemisio requested changes
нужно пройтись по замечаниям и исправить их

2016-12-07 20:32 UTC, senor-artemisio approved these changes

2016-12-22 17:21 UTC, senor-artemisio approved these changes

2016-12-23 08:44 UTC, niksamokhvalov requested changes

2016-12-23 08:44 UTC, niksamokhvalov commented on lib/helper/AdminListHelper.php
> +					// TODO: старое удаление
todo?

2016-12-23 10:44 UTC, niksamokhvalov approved these changes

2016-12-23 10:44 UTC, merged