Исправление определения "0.00" как числа
DigitalWand/digitalwand.admin_helper pull request #69
Opened 2017-02-05 07:35 UTC by mrdim

Устранение ошибки. Теперь "0.00" считается числом.

2017-02-25 13:09 UTC, ASGAlex requested changes
Это может сломать работу виджета в некоторых случаях, как мне кажется. Функция используется как при валидации фильтра, так и при валидации введённых значений перед сохранением. Если поле в таблице INT, is_numeric пропустит строку +0123.45e6 - и глазом не моргнёт. И мы схватим ошибку на уровне сохранения в БД. 

Сейчас isNumber, конечно, ущербен, т.к. пытается любым доступным способом преобразовать входные данные в числовой вариант, и, в случае успеха, мы просто надеемся, что раз у isNumber получилось, то и у mysql тоже получится :-)

2017-02-27 08:07 UTC, mrdim commented
Спасибо за ответ. Но текущий код тоже пропустит строку '+0123.45e6'.

2017-02-27 08:12 UTC, ASGAlex commented
Блин, и точно :-) 
Так, ну в таком случае из двух зол ваше - меньшее. Тогда аппрувлю, в уме держим, что этот кусок  вообще надо бы починить.
Спасибо!

2017-02-27 08:12 UTC, ASGAlex approved these changes

2017-02-27 08:12 UTC, merged

2017-03-13 08:47 UTC, niksamokhvalov commented
> в уме держим, что этот кусок вообще надо бы починить.

@ASGAlex, заведи проблему, что бы ум освободить ;)